%% Generated by the Erlang ASN.1 compiler. Version: 5.0.14
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module HsmPubKeySpec.

-ifndef(_HSMPUBKEYSPEC_HRL_).
-define(_HSMPUBKEYSPEC_HRL_, true).

-record('HsmPubKey', {
  modulus,
  exponent
}).

-endif. %% _HSMPUBKEYSPEC_HRL_
